/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  // @Test
  // public void appHasAGreeting() {
  // App classUnderTest = new App();
  // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  // }

  @Test
  public void TestGetGreeting() {
    App classUnderTest = new App();
    assertEquals("こんにちは SEMonster", classUnderTest.getGreeting());
  }
}
